// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3B7hn88UiSoRlaEYPbKx5GgkaS-14vWc',
    appId: '1:979113434540:web:98a55dcdba096a192f6e09',
    messagingSenderId: '979113434540',
    projectId: 'sapo-challenges',
    authDomain: 'sapo-challenges.firebaseapp.com',
    storageBucket: 'sapo-challenges.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfSGU6-VsFzfJUmgMgAenoTGK_uygZRtk',
    appId: '1:979113434540:android:371aefe0685a5cb32f6e09',
    messagingSenderId: '979113434540',
    projectId: 'sapo-challenges',
    storageBucket: 'sapo-challenges.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCO3zb9sY2VoUwIw0Pwz7YYJJe_IM4fBbM',
    appId: '1:979113434540:ios:6f24ebd62d893ecb2f6e09',
    messagingSenderId: '979113434540',
    projectId: 'sapo-challenges',
    storageBucket: 'sapo-challenges.firebasestorage.app',
    iosBundleId: 'com.example.authenticationChallenge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCO3zb9sY2VoUwIw0Pwz7YYJJe_IM4fBbM',
    appId: '1:979113434540:ios:6f24ebd62d893ecb2f6e09',
    messagingSenderId: '979113434540',
    projectId: 'sapo-challenges',
    storageBucket: 'sapo-challenges.firebasestorage.app',
    iosBundleId: 'com.example.authenticationChallenge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3B7hn88UiSoRlaEYPbKx5GgkaS-14vWc',
    appId: '1:979113434540:web:4a218ce7a038f3a12f6e09',
    messagingSenderId: '979113434540',
    projectId: 'sapo-challenges',
    authDomain: 'sapo-challenges.firebaseapp.com',
    storageBucket: 'sapo-challenges.firebasestorage.app',
  );
}
