// Mocks generated by Mockito 5.4.5 from annotations
// in authentication_challenge/test/view_models/email_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:authentication_challenge/repositories/repository.dart' as _i3;
import 'package:authentication_challenge/utils/validators.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [Validator].
///
/// See the documentation for Mockito's code generation for more information.
class MockValidator extends _i1.Mock implements _i2.Validator {
  MockValidator() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String? validateEmail(String? email) =>
      (super.noSuchMethod(Invocation.method(#validateEmail, [email]))
          as String?);

  @override
  String? validateCode(String? code) =>
      (super.noSuchMethod(Invocation.method(#validateCode, [code])) as String?);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i3.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<String?> callHelloWorld() =>
      (super.noSuchMethod(
            Invocation.method(#callHelloWorld, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<Map<String, dynamic>?> sendAuthCode(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#sendAuthCode, [email]),
            returnValue: _i4.Future<Map<String, dynamic>?>.value(),
          )
          as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<void> deleteAuthCode(String? verificationId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAuthCode, [verificationId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>?> verifyAuthCode(
    String? verificationId,
    String? code,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyAuthCode, [verificationId, code]),
            returnValue: _i4.Future<Map<String, dynamic>?>.value(),
          )
          as _i4.Future<Map<String, dynamic>?>);
}
